apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syft-sbom-output
  namespace: sbom
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 5Gi
