apiVersion: v1
kind: Secret
metadata:
  name: dependency-track-db
  namespace: dependency-track
type: Opaque
stringData:
  password: CHANGE_ME_DB_PASSWORD
  postgres-password: CHANGE_ME_POSTGRES_PASSWORD
