apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-track-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dwetmore/dependency-track-syft-gitops.git
    targetRevision: main
    path: workloads/dependency-track-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: dependency-track
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
