apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-track
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dependencytrack.github.io/helm-charts
    chart: dependency-track
    targetRevision: 0.42.0
    helm:
      values: |
        common:
          secretKey:
            createSecret: true

        apiServer:
          persistentVolume:
            enabled: true
            className: microk8s-hostpath
            size: 10Gi
          extraEnv:
            - name: ALPINE_DATABASE_MODE
              value: external
            - name: ALPINE_DATABASE_URL
              value: jdbc:postgresql://dependency-track-postgresql.dependency-track.svc.cluster.local:5432/dtrack
            - name: ALPINE_DATABASE_DRIVER
              value: org.postgresql.Driver
            - name: ALPINE_DATABASE_USERNAME
              value: dtrack
            - name: ALPINE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dependency-track-db
                  key: password
          service:
            type: ClusterIP

        frontend:
          apiBaseUrl: ""
          service:
            type: ClusterIP
        extraObjects:
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: dependency-track-frontend
              annotations:
                nginx.ingress.kubernetes.io/ssl-redirect: "false"
            spec:
              rules:
                - host: dtrack.172.17.93.185.nip.io
                  http:
                    paths:
                      - path: /api
                        pathType: Prefix
                        backend:
                          service:
                            name: dependency-track-api-server
                            port:
                              number: 8080
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: dependency-track-frontend
                            port:
                              number: 8080
  destination:
    server: https://kubernetes.default.svc
    namespace: dependency-track
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
